stages:
  - install

install_dependencies:
  stage: install
  image: node:18-alpine
  tags:
    - docker
  script:
    - npm install --force
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull
  only:
    refs:
      - merge_requests
      - main
      - dev
    changes:
      - package-lock.json
