stages:
  - install
  - build_and_test

variables:
  PROJECT_PATH: "$CI_PROJECT_DIR"
  APP_OUTPUT_PATH: "$CI_PROJECT_DIR/artifacts/app"

install_dependencies:
  stage: install
  image: node:18-alpine
  tags:
    - docker
  script:
    - npm install --force
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull
  only:
    refs:
      - merge_requests
      - main
    changes:
      - package-lock.json

build_app:
  stage: build_and_test
  image: node:18-alpine
  tags:
    - docker
  script:
    - npm run build
#  after_script:
#    - cp $PROJECT_PATH/Dockerfile $APP_OUTPUT_PATH
  artifacts:
    name: "angular-app-pipeline"
    paths:
      - $APP_OUTPUT_PATH
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull
